using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpectrumSharing
{
    public class AuctionEvent
    {
        public string TimeStamp { get; set; }
        public string LogType { get; set; }
        public string TransactionID { get; set; }
        public string AllocatedChannel { get; set; }
        public string WinnerSecondaryUserID { get; set; }
        public string WinnerSecondaryUserWallet { get; set; }
        public string WinnerSecondaryUserReputationScore { get; set; }
        public string PrimaryUserID { get; set; }
        public string PrimaryUserWallet { get; set; }
        public string PrimaryUserReputationScore { get; set; }
        public string PrimaryUserStatus { get; set; }
        public string AuctionNo { get; set; }
        public string AuctionChannel { get; set; }
        public string AuctionChannelBandwidth { get; set; }
        public string PrimaryUserAuctionCount { get; set; }
        public string PrimaryUserSuccessfulAuctionCount { get; set; }
        public string ResponseIsAppropriate { get; set; }
        public string AppropriateResponseCount { get; set; }
        public string TotalRequestCount { get; set; }
        public string AvailableSpectrumKHz { get; set; }
        public string TotalSpectrumKHz { get; set; }
        public string Channel1 { get; set; }
        public string Channel2 { get; set; }
        public string Channel3 { get; set; }
        public string Channel4 { get; set; }
        public string Channel5 { get; set; }
        public string Channel6 { get; set; }
        public string Channel7 { get; set; }
        public string Channel8 { get; set; }
        public string Channel9 { get; set; }
        public string Channel10 { get; set; }
        public string Channel11 { get; set; }
        public string Channel12 { get; set; }
        public string Channel13 { get; set; }
        public string Channel14 { get; set; }
        public string Channel15 { get; set; }
        public string Channel16 { get; set; }
        public string Channel17 { get; set; }
        public string Channel18 { get; set; }
        public string Channel19 { get; set; }
        public string Channel20 { get; set; }
        public string Channel21 { get; set; }
        public string Channel22 { get; set; }
        public string Channel23 { get; set; }
        public string Channel24 { get; set; }
        public string Channel25 { get; set; }
        public string Channel26 { get; set; }
        public string Channel27 { get; set; }
        public string Channel28 { get; set; }
        public string Channel29 { get; set; }
        public string Channel30 { get; set; }
        public string Channel31 { get; set; }
        public string Channel32 { get; set; }
        public string Channel33 { get; set; }
        public string Channel34 { get; set; }
        public string Channel35 { get; set; }
        public string Channel36 { get; set; }
        public string Channel37 { get; set; }
        public string Channel38 { get; set; }
        public string Channel39 { get; set; }
        public string Channel40 { get; set; }
        public string Channel41 { get; set; }
        public string Channel42 { get; set; }
        public string Channel43 { get; set; }
        public string Channel44 { get; set; }
        public string Channel45 { get; set; }
        public string Channel46 { get; set; }
        public string Channel47 { get; set; }
        public string Channel48 { get; set; }
        public string Channel49 { get; set; }
        public string Channel50 { get; set; }
        public string Channel51 { get; set; }
        public string Channel52 { get; set; }
        public string Channel53 { get; set; }
        public string Channel54 { get; set; }
        public string Channel55 { get; set; }
        public string Channel56 { get; set; }
        public string Channel57 { get; set; }
        public string AuctionCountUser1 { get; set; }
        public string AuctionCountUser2 { get; set; }
        public string AuctionCountUser3 { get; set; }
        public string AuctionCountUser4 { get; set; }
        public string AuctionCountUser5 { get; set; }
        public string AuctionCountUser6 { get; set; }
        public string AuctionCountUser7 { get; set; }
        public string AuctionCountUser8 { get; set; }
        public string AuctionCountUser9 { get; set; }
        public string AuctionCountUser10 { get; set; }
        public string AuctionCountUser11 { get; set; }
        public string AuctionCountUser12 { get; set; }
        public string AuctionCountUser13 { get; set; }
        public string AuctionCountUser14 { get; set; }
        public string AuctionCountUser15 { get; set; }
        public string AuctionCountUser16 { get; set; }
        public string AuctionCountUser17 { get; set; }
        public string AuctionCountUser18 { get; set; }
        public string AuctionCountUser19 { get; set; }
        public string AuctionCountUser20 { get; set; }
        public string AuctionCountUser21 { get; set; }
        public string AuctionCountUser22 { get; set; }
        public string AuctionCountUser23 { get; set; }
        public string AuctionCountUser24 { get; set; }
        public string AuctionCountUser25 { get; set; }
        public string AuctionCountUser26 { get; set; }
        public string AuctionCountUser27 { get; set; }
        public string AuctionCountUser28 { get; set; }
        public string AuctionCountUser29 { get; set; }
        public string AuctionCountUser30 { get; set; }
        public string AuctionCountUser31 { get; set; }
        public string AuctionCountUser32 { get; set; }
        public string AuctionCountUser33 { get; set; }
        public string AuctionCountUser34 { get; set; }
        public string AuctionCountUser35 { get; set; }
        public string AuctionCountUser36 { get; set; }
        public string AuctionCountUser37 { get; set; }
        public string AuctionCountUser38 { get; set; }
        public string AuctionCountUser39 { get; set; }
        public string AuctionCountUser40 { get; set; }
        public string AuctionCountUser41 { get; set; }
        public string AuctionCountUser42 { get; set; }
        public string AuctionCountUser43 { get; set; }
        public string AuctionCountUser44 { get; set; }
        public string AuctionCountUser45 { get; set; }
        public string AuctionCountUser46 { get; set; }
        public string AuctionCountUser47 { get; set; }
        public string AuctionCountUser48 { get; set; }
        public string AuctionCountUser49 { get; set; }
        public string AuctionCountUser50 { get; set; }
        public string AuctionCountUser51 { get; set; }
        public string AuctionCountUser52 { get; set; }
        public string AuctionCountUser53 { get; set; }
        public string AuctionCountUser54 { get; set; }
        public string AuctionCountUser55 { get; set; }
        public string AuctionCountUser56 { get; set; }
        public string AuctionCountUser57 { get; set; }
        public string AuctionCountUser58 { get; set; }
        public string AuctionCountUser59 { get; set; }
        public string AuctionCountUser60 { get; set; }
        public string AuctionCountUser61 { get; set; }
        public string AuctionCountUser62 { get; set; }
        public string AuctionCountUser63 { get; set; }
        public string AuctionCountUser64 { get; set; }
        public string AuctionCountUser65 { get; set; }
        public string AuctionCountUser66 { get; set; }
        public string AuctionCountUser67 { get; set; }
        public string IsBiddingUser1 { get; set; }
        public string IsBiddingUser2 { get; set; }
        public string IsBiddingUser3 { get; set; }
        public string IsBiddingUser4 { get; set; }
        public string IsBiddingUser5 { get; set; }
        public string IsBiddingUser6 { get; set; }
        public string IsBiddingUser7 { get; set; }
        public string IsBiddingUser8 { get; set; }
        public string IsBiddingUser9 { get; set; }
        public string IsBiddingUser10 { get; set; }
        public string IsBiddingUser11 { get; set; }
        public string IsBiddingUser12 { get; set; }
        public string IsBiddingUser13 { get; set; }
        public string IsBiddingUser14 { get; set; }
        public string IsBiddingUser15 { get; set; }
        public string IsBiddingUser16 { get; set; }
        public string IsBiddingUser17 { get; set; }
        public string IsBiddingUser18 { get; set; }
        public string IsBiddingUser19 { get; set; }
        public string IsBiddingUser20 { get; set; }
        public string IsBiddingUser21 { get; set; }
        public string IsBiddingUser22 { get; set; }
        public string IsBiddingUser23 { get; set; }
        public string IsBiddingUser24 { get; set; }
        public string IsBiddingUser25 { get; set; }
        public string IsBiddingUser26 { get; set; }
        public string IsBiddingUser27 { get; set; }
        public string IsBiddingUser28 { get; set; }
        public string IsBiddingUser29 { get; set; }
        public string IsBiddingUser30 { get; set; }
        public string IsBiddingUser31 { get; set; }
        public string IsBiddingUser32 { get; set; }
        public string IsBiddingUser33 { get; set; }
        public string IsBiddingUser34 { get; set; }
        public string IsBiddingUser35 { get; set; }
        public string IsBiddingUser36 { get; set; }
        public string IsBiddingUser37 { get; set; }
        public string IsBiddingUser38 { get; set; }
        public string IsBiddingUser39 { get; set; }
        public string IsBiddingUser40 { get; set; }
        public string IsBiddingUser41 { get; set; }
        public string IsBiddingUser42 { get; set; }
        public string IsBiddingUser43 { get; set; }
        public string IsBiddingUser44 { get; set; }
        public string IsBiddingUser45 { get; set; }
        public string IsBiddingUser46 { get; set; }
        public string IsBiddingUser47 { get; set; }
        public string IsBiddingUser48 { get; set; }
        public string IsBiddingUser49 { get; set; }
        public string IsBiddingUser50 { get; set; }
        public string IsBiddingUser51 { get; set; }
        public string IsBiddingUser52 { get; set; }
        public string IsBiddingUser53 { get; set; }
        public string IsBiddingUser54 { get; set; }
        public string IsBiddingUser55 { get; set; }
        public string IsBiddingUser56 { get; set; }
        public string IsBiddingUser57 { get; set; }
        public string IsBiddingUser58 { get; set; }
        public string IsBiddingUser59 { get; set; }
        public string IsBiddingUser60 { get; set; }
        public string IsBiddingUser61 { get; set; }
        public string IsBiddingUser62 { get; set; }
        public string IsBiddingUser63 { get; set; }
        public string IsBiddingUser64 { get; set; }
        public string IsBiddingUser65 { get; set; }
        public string IsBiddingUser66 { get; set; }
        public string IsBiddingUser67 { get; set; }
        public string IsInPoolUser1 { get; set; }
        public string IsInPoolUser2 { get; set; }
        public string IsInPoolUser3 { get; set; }
        public string IsInPoolUser4 { get; set; }
        public string IsInPoolUser5 { get; set; }
        public string IsInPoolUser6 { get; set; }
        public string IsInPoolUser7 { get; set; }
        public string IsInPoolUser8 { get; set; }
        public string IsInPoolUser9 { get; set; }
        public string IsInPoolUser10 { get; set; }
        public string IsInPoolUser11 { get; set; }
        public string IsInPoolUser12 { get; set; }
        public string IsInPoolUser13 { get; set; }
        public string IsInPoolUser14 { get; set; }
        public string IsInPoolUser15 { get; set; }
        public string IsInPoolUser16 { get; set; }
        public string IsInPoolUser17 { get; set; }
        public string IsInPoolUser18 { get; set; }
        public string IsInPoolUser19 { get; set; }
        public string IsInPoolUser20 { get; set; }
        public string IsInPoolUser21 { get; set; }
        public string IsInPoolUser22 { get; set; }
        public string IsInPoolUser23 { get; set; }
        public string IsInPoolUser24 { get; set; }
        public string IsInPoolUser25 { get; set; }
        public string IsInPoolUser26 { get; set; }
        public string IsInPoolUser27 { get; set; }
        public string IsInPoolUser28 { get; set; }
        public string IsInPoolUser29 { get; set; }
        public string IsInPoolUser30 { get; set; }
        public string IsInPoolUser31 { get; set; }
        public string IsInPoolUser32 { get; set; }
        public string IsInPoolUser33 { get; set; }
        public string IsInPoolUser34 { get; set; }
        public string IsInPoolUser35 { get; set; }
        public string IsInPoolUser36 { get; set; }
        public string IsInPoolUser37 { get; set; }
        public string IsInPoolUser38 { get; set; }
        public string IsInPoolUser39 { get; set; }
        public string IsInPoolUser40 { get; set; }
        public string IsInPoolUser41 { get; set; }
        public string IsInPoolUser42 { get; set; }
        public string IsInPoolUser43 { get; set; }
        public string IsInPoolUser44 { get; set; }
        public string IsInPoolUser45 { get; set; }
        public string IsInPoolUser46 { get; set; }
        public string IsInPoolUser47 { get; set; }
        public string IsInPoolUser48 { get; set; }
        public string IsInPoolUser49 { get; set; }
        public string IsInPoolUser50 { get; set; }
        public string IsInPoolUser51 { get; set; }
        public string IsInPoolUser52 { get; set; }
        public string IsInPoolUser53 { get; set; }
        public string IsInPoolUser54 { get; set; }
        public string IsInPoolUser55 { get; set; }
        public string IsInPoolUser56 { get; set; }
        public string IsInPoolUser57 { get; set; }
        public string IsInPoolUser58 { get; set; }
        public string IsInPoolUser59 { get; set; }
        public string IsInPoolUser60 { get; set; }
        public string IsInPoolUser61 { get; set; }
        public string IsInPoolUser62 { get; set; }
        public string IsInPoolUser63 { get; set; }
        public string IsInPoolUser64 { get; set; }
        public string IsInPoolUser65 { get; set; }
        public string IsInPoolUser66 { get; set; }
        public string IsInPoolUser67 { get; set; }
        public string ScoreUser1 { get; set; }
        public string ScoreUser2 { get; set; }
        public string ScoreUser3 { get; set; }
        public string ScoreUser4 { get; set; }
        public string ScoreUser5 { get; set; }
        public string ScoreUser6 { get; set; }
        public string ScoreUser7 { get; set; }
        public string ScoreUser8 { get; set; }
        public string ScoreUser9 { get; set; }
        public string ScoreUser10 { get; set; }
        public string ScoreUser11 { get; set; }
        public string ScoreUser12 { get; set; }
        public string ScoreUser13 { get; set; }
        public string ScoreUser14 { get; set; }
        public string ScoreUser15 { get; set; }
        public string ScoreUser16 { get; set; }
        public string ScoreUser17 { get; set; }
        public string ScoreUser18 { get; set; }
        public string ScoreUser19 { get; set; }
        public string ScoreUser20 { get; set; }
        public string ScoreUser21 { get; set; }
        public string ScoreUser22 { get; set; }
        public string ScoreUser23 { get; set; }
        public string ScoreUser24 { get; set; }
        public string ScoreUser25 { get; set; }
        public string ScoreUser26 { get; set; }
        public string ScoreUser27 { get; set; }
        public string ScoreUser28 { get; set; }
        public string ScoreUser29 { get; set; }
        public string ScoreUser30 { get; set; }
        public string ScoreUser31 { get; set; }
        public string ScoreUser32 { get; set; }
        public string ScoreUser33 { get; set; }
        public string ScoreUser34 { get; set; }
        public string ScoreUser35 { get; set; }
        public string ScoreUser36 { get; set; }
        public string ScoreUser37 { get; set; }
        public string ScoreUser38 { get; set; }
        public string ScoreUser39 { get; set; }
        public string ScoreUser40 { get; set; }
        public string ScoreUser41 { get; set; }
        public string ScoreUser42 { get; set; }
        public string ScoreUser43 { get; set; }
        public string ScoreUser44 { get; set; }
        public string ScoreUser45 { get; set; }
        public string ScoreUser46 { get; set; }
        public string ScoreUser47 { get; set; }
        public string ScoreUser48 { get; set; }
        public string ScoreUser49 { get; set; }
        public string ScoreUser50 { get; set; }
        public string ScoreUser51 { get; set; }
        public string ScoreUser52 { get; set; }
        public string ScoreUser53 { get; set; }
        public string ScoreUser54 { get; set; }
        public string ScoreUser55 { get; set; }
        public string ScoreUser56 { get; set; }
        public string ScoreUser57 { get; set; }
        public string ScoreUser58 { get; set; }
        public string ScoreUser59 { get; set; }
        public string ScoreUser60 { get; set; }
        public string ScoreUser61 { get; set; }
        public string ScoreUser62 { get; set; }
        public string ScoreUser63 { get; set; }
        public string ScoreUser64 { get; set; }
        public string ScoreUser65 { get; set; }
        public string ScoreUser66 { get; set; }
        public string ScoreUser67 { get; set; }
        public string StatusUser1 { get; set; }
        public string StatusUser2 { get; set; }
        public string StatusUser3 { get; set; }
        public string StatusUser4 { get; set; }
        public string StatusUser5 { get; set; }
        public string StatusUser6 { get; set; }
        public string StatusUser7 { get; set; }
        public string StatusUser8 { get; set; }
        public string StatusUser9 { get; set; }
        public string StatusUser10 { get; set; }
        public string StatusUser11 { get; set; }
        public string StatusUser12 { get; set; }
        public string StatusUser13 { get; set; }
        public string StatusUser14 { get; set; }
        public string StatusUser15 { get; set; }
        public string StatusUser16 { get; set; }
        public string StatusUser17 { get; set; }
        public string StatusUser18 { get; set; }
        public string StatusUser19 { get; set; }
        public string StatusUser20 { get; set; }
        public string StatusUser21 { get; set; }
        public string StatusUser22 { get; set; }
        public string StatusUser23 { get; set; }
        public string StatusUser24 { get; set; }
        public string StatusUser25 { get; set; }
        public string StatusUser26 { get; set; }
        public string StatusUser27 { get; set; }
        public string StatusUser28 { get; set; }
        public string StatusUser29 { get; set; }
        public string StatusUser30 { get; set; }
        public string StatusUser31 { get; set; }
        public string StatusUser32 { get; set; }
        public string StatusUser33 { get; set; }
        public string StatusUser34 { get; set; }
        public string StatusUser35 { get; set; }
        public string StatusUser36 { get; set; }
        public string StatusUser37 { get; set; }
        public string StatusUser38 { get; set; }
        public string StatusUser39 { get; set; }
        public string StatusUser40 { get; set; }
        public string StatusUser41 { get; set; }
        public string StatusUser42 { get; set; }
        public string StatusUser43 { get; set; }
        public string StatusUser44 { get; set; }
        public string StatusUser45 { get; set; }
        public string StatusUser46 { get; set; }
        public string StatusUser47 { get; set; }
        public string StatusUser48 { get; set; }
        public string StatusUser49 { get; set; }
        public string StatusUser50 { get; set; }
        public string StatusUser51 { get; set; }
        public string StatusUser52 { get; set; }
        public string StatusUser53 { get; set; }
        public string StatusUser54 { get; set; }
        public string StatusUser55 { get; set; }
        public string StatusUser56 { get; set; }
        public string StatusUser57 { get; set; }
        public string StatusUser58 { get; set; }
        public string StatusUser59 { get; set; }
        public string StatusUser60 { get; set; }
        public string StatusUser61 { get; set; }
        public string StatusUser62 { get; set; }
        public string StatusUser63 { get; set; }
        public string StatusUser64 { get; set; }
        public string StatusUser65 { get; set; }
        public string StatusUser66 { get; set; }
        public string StatusUser67 { get; set; }
        public string SuccessfulAuctionCountUser1 { get; set; }
        public string SuccessfulAuctionCountUser2 { get; set; }
        public string SuccessfulAuctionCountUser3 { get; set; }
        public string SuccessfulAuctionCountUser4 { get; set; }
        public string SuccessfulAuctionCountUser5 { get; set; }
        public string SuccessfulAuctionCountUser6 { get; set; }
        public string SuccessfulAuctionCountUser7 { get; set; }
        public string SuccessfulAuctionCountUser8 { get; set; }
        public string SuccessfulAuctionCountUser9 { get; set; }
        public string SuccessfulAuctionCountUser10 { get; set; }
        public string SuccessfulAuctionCountUser11 { get; set; }
        public string SuccessfulAuctionCountUser12 { get; set; }
        public string SuccessfulAuctionCountUser13 { get; set; }
        public string SuccessfulAuctionCountUser14 { get; set; }
        public string SuccessfulAuctionCountUser15 { get; set; }
        public string SuccessfulAuctionCountUser16 { get; set; }
        public string SuccessfulAuctionCountUser17 { get; set; }
        public string SuccessfulAuctionCountUser18 { get; set; }
        public string SuccessfulAuctionCountUser19 { get; set; }
        public string SuccessfulAuctionCountUser20 { get; set; }
        public string SuccessfulAuctionCountUser21 { get; set; }
        public string SuccessfulAuctionCountUser22 { get; set; }
        public string SuccessfulAuctionCountUser23 { get; set; }
        public string SuccessfulAuctionCountUser24 { get; set; }
        public string SuccessfulAuctionCountUser25 { get; set; }
        public string SuccessfulAuctionCountUser26 { get; set; }
        public string SuccessfulAuctionCountUser27 { get; set; }
        public string SuccessfulAuctionCountUser28 { get; set; }
        public string SuccessfulAuctionCountUser29 { get; set; }
        public string SuccessfulAuctionCountUser30 { get; set; }
        public string SuccessfulAuctionCountUser31 { get; set; }
        public string SuccessfulAuctionCountUser32 { get; set; }
        public string SuccessfulAuctionCountUser33 { get; set; }
        public string SuccessfulAuctionCountUser34 { get; set; }
        public string SuccessfulAuctionCountUser35 { get; set; }
        public string SuccessfulAuctionCountUser36 { get; set; }
        public string SuccessfulAuctionCountUser37 { get; set; }
        public string SuccessfulAuctionCountUser38 { get; set; }
        public string SuccessfulAuctionCountUser39 { get; set; }
        public string SuccessfulAuctionCountUser40 { get; set; }
        public string SuccessfulAuctionCountUser41 { get; set; }
        public string SuccessfulAuctionCountUser42 { get; set; }
        public string SuccessfulAuctionCountUser43 { get; set; }
        public string SuccessfulAuctionCountUser44 { get; set; }
        public string SuccessfulAuctionCountUser45 { get; set; }
        public string SuccessfulAuctionCountUser46 { get; set; }
        public string SuccessfulAuctionCountUser47 { get; set; }
        public string SuccessfulAuctionCountUser48 { get; set; }
        public string SuccessfulAuctionCountUser49 { get; set; }
        public string SuccessfulAuctionCountUser50 { get; set; }
        public string SuccessfulAuctionCountUser51 { get; set; }
        public string SuccessfulAuctionCountUser52 { get; set; }
        public string SuccessfulAuctionCountUser53 { get; set; }
        public string SuccessfulAuctionCountUser54 { get; set; }
        public string SuccessfulAuctionCountUser55 { get; set; }
        public string SuccessfulAuctionCountUser56 { get; set; }
        public string SuccessfulAuctionCountUser57 { get; set; }
        public string SuccessfulAuctionCountUser58 { get; set; }
        public string SuccessfulAuctionCountUser59 { get; set; }
        public string SuccessfulAuctionCountUser60 { get; set; }
        public string SuccessfulAuctionCountUser61 { get; set; }
        public string SuccessfulAuctionCountUser62 { get; set; }
        public string SuccessfulAuctionCountUser63 { get; set; }
        public string SuccessfulAuctionCountUser64 { get; set; }
        public string SuccessfulAuctionCountUser65 { get; set; }
        public string SuccessfulAuctionCountUser66 { get; set; }
        public string SuccessfulAuctionCountUser67 { get; set; }
        public string WalletUser1 { get; set; }
        public string WalletUser2 { get; set; }
        public string WalletUser3 { get; set; }
        public string WalletUser4 { get; set; }
        public string WalletUser5 { get; set; }
        public string WalletUser6 { get; set; }
        public string WalletUser7 { get; set; }
        public string WalletUser8 { get; set; }
        public string WalletUser9 { get; set; }
        public string WalletUser10 { get; set; }
        public string WalletUser11 { get; set; }
        public string WalletUser12 { get; set; }
        public string WalletUser13 { get; set; }
        public string WalletUser14 { get; set; }
        public string WalletUser15 { get; set; }
        public string WalletUser16 { get; set; }
        public string WalletUser17 { get; set; }
        public string WalletUser18 { get; set; }
        public string WalletUser19 { get; set; }
        public string WalletUser20 { get; set; }
        public string WalletUser21 { get; set; }
        public string WalletUser22 { get; set; }
        public string WalletUser23 { get; set; }
        public string WalletUser24 { get; set; }
        public string WalletUser25 { get; set; }
        public string WalletUser26 { get; set; }
        public string WalletUser27 { get; set; }
        public string WalletUser28 { get; set; }
        public string WalletUser29 { get; set; }
        public string WalletUser30 { get; set; }
        public string WalletUser31 { get; set; }
        public string WalletUser32 { get; set; }
        public string WalletUser33 { get; set; }
        public string WalletUser34 { get; set; }
        public string WalletUser35 { get; set; }
        public string WalletUser36 { get; set; }
        public string WalletUser37 { get; set; }
        public string WalletUser38 { get; set; }
        public string WalletUser39 { get; set; }
        public string WalletUser40 { get; set; }
        public string WalletUser41 { get; set; }
        public string WalletUser42 { get; set; }
        public string WalletUser43 { get; set; }
        public string WalletUser44 { get; set; }
        public string WalletUser45 { get; set; }
        public string WalletUser46 { get; set; }
        public string WalletUser47 { get; set; }
        public string WalletUser48 { get; set; }
        public string WalletUser49 { get; set; }
        public string WalletUser50 { get; set; }
        public string WalletUser51 { get; set; }
        public string WalletUser52 { get; set; }
        public string WalletUser53 { get; set; }
        public string WalletUser54 { get; set; }
        public string WalletUser55 { get; set; }
        public string WalletUser56 { get; set; }
        public string WalletUser57 { get; set; }
        public string WalletUser58 { get; set; }
        public string WalletUser59 { get; set; }
        public string WalletUser60 { get; set; }
        public string WalletUser61 { get; set; }
        public string WalletUser62 { get; set; }
        public string WalletUser63 { get; set; }
        public string WalletUser64 { get; set; }
        public string WalletUser65 { get; set; }
        public string WalletUser66 { get; set; }
        public string WalletUser67 { get; set; }
        public string AuctionPrice { get; set; }
    }
}
