using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpectrumSharing
{
    public static class Queries
    {
        public const string connectDB = @"Data Source=PRJ-MESENERGIN\SQLEXPRESS;
                                                     Initial Catalog=SpectrumSharingDB;
                                                     Integrated Security=True;
                                                     Connect Timeout=30;
                                                     Encrypt=False;
                                                     TrustServerCertificate=False;
                                                     ApplicationIntent=ReadWrite;
                                                     MultiSubnetFailover=False";
        public static string insertQuery = @"INSERT INTO [dbo].[TransactionLog]
                                              ([TimeStamp]
                                              ,[LogType]
                                              ,[TransactionID]
                                              ,[AllocatedChannel]
                                              ,[WinnerSecondaryUserID]
                                              ,[WinnerSecondaryUserWallet]
                                              ,[WinnerSecondaryUserReputationScore]
                                              ,[PrimaryUserID]
                                              ,[PrimaryUserWallet]
                                              ,[PrimaryUserReputationScore]
                                              ,[PrimaryUserStatus]
                                              ,[AuctionNo]
                                              ,[AuctionChannel]
                                              ,[AuctionChannelBandwidth]
                                              ,[PrimaryUserAuctionCount]
                                              ,[PrimaryUserSuccessfulAuctionCount]
                                              ,[ResponseIsAppropriate]
                                              ,[AppropriateResponseCount]
                                              ,[TotalRequestCount]
                                              ,[AvailableSpectrumKHz]
                                              ,[TotalSpectrumKHz]
                                              ,[Channel1]
                                              ,[Channel2]
                                              ,[Channel3]
                                              ,[Channel4]
                                              ,[Channel5]
                                              ,[Channel6]
                                              ,[Channel7]
                                              ,[Channel8]
                                              ,[Channel9]
                                              ,[Channel10]
                                              ,[Channel11]
                                              ,[Channel12]
                                              ,[Channel13]
                                              ,[Channel14]
                                              ,[Channel15]
                                              ,[Channel16]
                                              ,[Channel17]
                                              ,[Channel18]
                                              ,[Channel19]
                                              ,[Channel20]
                                              ,[Channel21]
                                              ,[Channel22]
                                              ,[Channel23]
                                              ,[Channel24]
                                              ,[Channel25]
                                              ,[Channel26]
                                              ,[Channel27]
                                              ,[Channel28]
                                              ,[Channel29]
                                              ,[Channel30]
                                              ,[Channel31]
                                              ,[Channel32]
                                              ,[Channel33]
                                              ,[Channel34]
                                              ,[Channel35]
                                              ,[Channel36]
                                              ,[Channel37]
                                              ,[Channel38]
                                              ,[Channel39]
                                              ,[Channel40]
                                              ,[Channel41]
                                              ,[Channel42]
                                              ,[Channel43]
                                              ,[Channel44]
                                              ,[Channel45]
                                              ,[Channel46]
                                              ,[Channel47]
                                              ,[Channel48]
                                              ,[Channel49]
                                              ,[Channel50]
                                              ,[Channel51]
                                              ,[Channel52]
                                              ,[Channel53]
                                              ,[Channel54]
                                              ,[Channel55]
                                              ,[Channel56]
                                              ,[Channel57]
                                              ,[AuctionCountUser1]
                                              ,[AuctionCountUser2]
                                              ,[AuctionCountUser3]
                                              ,[AuctionCountUser4]
                                              ,[AuctionCountUser5]
                                              ,[AuctionCountUser6]
                                              ,[AuctionCountUser7]
                                              ,[AuctionCountUser8]
                                              ,[AuctionCountUser9]
                                              ,[AuctionCountUser10]
                                              ,[AuctionCountUser11]
                                              ,[AuctionCountUser12]
                                              ,[AuctionCountUser13]
                                              ,[AuctionCountUser14]
                                              ,[AuctionCountUser15]
                                              ,[AuctionCountUser16]
                                              ,[AuctionCountUser17]
                                              ,[AuctionCountUser18]
                                              ,[AuctionCountUser19]
                                              ,[AuctionCountUser20]
                                              ,[AuctionCountUser21]
                                              ,[AuctionCountUser22]
                                              ,[AuctionCountUser23]
                                              ,[AuctionCountUser24]
                                              ,[AuctionCountUser25]
                                              ,[AuctionCountUser26]
                                              ,[AuctionCountUser27]
                                              ,[AuctionCountUser28]
                                              ,[AuctionCountUser29]
                                              ,[AuctionCountUser30]
                                              ,[AuctionCountUser31]
                                              ,[AuctionCountUser32]
                                              ,[AuctionCountUser33]
                                              ,[AuctionCountUser34]
                                              ,[AuctionCountUser35]
                                              ,[AuctionCountUser36]
                                              ,[AuctionCountUser37]
                                              ,[AuctionCountUser38]
                                              ,[AuctionCountUser39]
                                              ,[AuctionCountUser40]
                                              ,[AuctionCountUser41]
                                              ,[AuctionCountUser42]
                                              ,[AuctionCountUser43]
                                              ,[AuctionCountUser44]
                                              ,[AuctionCountUser45]
                                              ,[AuctionCountUser46]
                                              ,[AuctionCountUser47]
                                              ,[AuctionCountUser48]
                                              ,[AuctionCountUser49]
                                              ,[AuctionCountUser50]
                                              ,[AuctionCountUser51]
                                              ,[AuctionCountUser52]
                                              ,[AuctionCountUser53]
                                              ,[AuctionCountUser54]
                                              ,[AuctionCountUser55]
                                              ,[AuctionCountUser56]
                                              ,[AuctionCountUser57]
                                              ,[AuctionCountUser58]
                                              ,[AuctionCountUser59]
                                              ,[AuctionCountUser60]
                                              ,[AuctionCountUser61]
                                              ,[AuctionCountUser62]
                                              ,[AuctionCountUser63]
                                              ,[AuctionCountUser64]
                                              ,[AuctionCountUser65]
                                              ,[AuctionCountUser66]
                                              ,[AuctionCountUser67]
                                              ,[IsBiddingUser1]
                                              ,[IsBiddingUser2]
                                              ,[IsBiddingUser3]
                                              ,[IsBiddingUser4]
                                              ,[IsBiddingUser5]
                                              ,[IsBiddingUser6]
                                              ,[IsBiddingUser7]
                                              ,[IsBiddingUser8]
                                              ,[IsBiddingUser9]
                                              ,[IsBiddingUser10]
                                              ,[IsBiddingUser11]
                                              ,[IsBiddingUser12]
                                              ,[IsBiddingUser13]
                                              ,[IsBiddingUser14]
                                              ,[IsBiddingUser15]
                                              ,[IsBiddingUser16]
                                              ,[IsBiddingUser17]
                                              ,[IsBiddingUser18]
                                              ,[IsBiddingUser19]
                                              ,[IsBiddingUser20]
                                              ,[IsBiddingUser21]
                                              ,[IsBiddingUser22]
                                              ,[IsBiddingUser23]
                                              ,[IsBiddingUser24]
                                              ,[IsBiddingUser25]
                                              ,[IsBiddingUser26]
                                              ,[IsBiddingUser27]
                                              ,[IsBiddingUser28]
                                              ,[IsBiddingUser29]
                                              ,[IsBiddingUser30]
                                              ,[IsBiddingUser31]
                                              ,[IsBiddingUser32]
                                              ,[IsBiddingUser33]
                                              ,[IsBiddingUser34]
                                              ,[IsBiddingUser35]
                                              ,[IsBiddingUser36]
                                              ,[IsBiddingUser37]
                                              ,[IsBiddingUser38]
                                              ,[IsBiddingUser39]
                                              ,[IsBiddingUser40]
                                              ,[IsBiddingUser41]
                                              ,[IsBiddingUser42]
                                              ,[IsBiddingUser43]
                                              ,[IsBiddingUser44]
                                              ,[IsBiddingUser45]
                                              ,[IsBiddingUser46]
                                              ,[IsBiddingUser47]
                                              ,[IsBiddingUser48]
                                              ,[IsBiddingUser49]
                                              ,[IsBiddingUser50]
                                              ,[IsBiddingUser51]
                                              ,[IsBiddingUser52]
                                              ,[IsBiddingUser53]
                                              ,[IsBiddingUser54]
                                              ,[IsBiddingUser55]
                                              ,[IsBiddingUser56]
                                              ,[IsBiddingUser57]
                                              ,[IsBiddingUser58]
                                              ,[IsBiddingUser59]
                                              ,[IsBiddingUser60]
                                              ,[IsBiddingUser61]
                                              ,[IsBiddingUser62]
                                              ,[IsBiddingUser63]
                                              ,[IsBiddingUser64]
                                              ,[IsBiddingUser65]
                                              ,[IsBiddingUser66]
                                              ,[IsBiddingUser67]
                                              ,[IsInPoolUser1]
                                              ,[IsInPoolUser2]
                                              ,[IsInPoolUser3]
                                              ,[IsInPoolUser4]
                                              ,[IsInPoolUser5]
                                              ,[IsInPoolUser6]
                                              ,[IsInPoolUser7]
                                              ,[IsInPoolUser8]
                                              ,[IsInPoolUser9]
                                              ,[IsInPoolUser10]
                                              ,[IsInPoolUser11]
                                              ,[IsInPoolUser12]
                                              ,[IsInPoolUser13]
                                              ,[IsInPoolUser14]
                                              ,[IsInPoolUser15]
                                              ,[IsInPoolUser16]
                                              ,[IsInPoolUser17]
                                              ,[IsInPoolUser18]
                                              ,[IsInPoolUser19]
                                              ,[IsInPoolUser20]
                                              ,[IsInPoolUser21]
                                              ,[IsInPoolUser22]
                                              ,[IsInPoolUser23]
                                              ,[IsInPoolUser24]
                                              ,[IsInPoolUser25]
                                              ,[IsInPoolUser26]
                                              ,[IsInPoolUser27]
                                              ,[IsInPoolUser28]
                                              ,[IsInPoolUser29]
                                              ,[IsInPoolUser30]
                                              ,[IsInPoolUser31]
                                              ,[IsInPoolUser32]
                                              ,[IsInPoolUser33]
                                              ,[IsInPoolUser34]
                                              ,[IsInPoolUser35]
                                              ,[IsInPoolUser36]
                                              ,[IsInPoolUser37]
                                              ,[IsInPoolUser38]
                                              ,[IsInPoolUser39]
                                              ,[IsInPoolUser40]
                                              ,[IsInPoolUser41]
                                              ,[IsInPoolUser42]
                                              ,[IsInPoolUser43]
                                              ,[IsInPoolUser44]
                                              ,[IsInPoolUser45]
                                              ,[IsInPoolUser46]
                                              ,[IsInPoolUser47]
                                              ,[IsInPoolUser48]
                                              ,[IsInPoolUser49]
                                              ,[IsInPoolUser50]
                                              ,[IsInPoolUser51]
                                              ,[IsInPoolUser52]
                                              ,[IsInPoolUser53]
                                              ,[IsInPoolUser54]
                                              ,[IsInPoolUser55]
                                              ,[IsInPoolUser56]
                                              ,[IsInPoolUser57]
                                              ,[IsInPoolUser58]
                                              ,[IsInPoolUser59]
                                              ,[IsInPoolUser60]
                                              ,[IsInPoolUser61]
                                              ,[IsInPoolUser62]
                                              ,[IsInPoolUser63]
                                              ,[IsInPoolUser64]
                                              ,[IsInPoolUser65]
                                              ,[IsInPoolUser66]
                                              ,[IsInPoolUser67]
                                              ,[ScoreUser1]
                                              ,[ScoreUser2]
                                              ,[ScoreUser3]
                                              ,[ScoreUser4]
                                              ,[ScoreUser5]
                                              ,[ScoreUser6]
                                              ,[ScoreUser7]
                                              ,[ScoreUser8]
                                              ,[ScoreUser9]
                                              ,[ScoreUser10]
                                              ,[ScoreUser11]
                                              ,[ScoreUser12]
                                              ,[ScoreUser13]
                                              ,[ScoreUser14]
                                              ,[ScoreUser15]
                                              ,[ScoreUser16]
                                              ,[ScoreUser17]
                                              ,[ScoreUser18]
                                              ,[ScoreUser19]
                                              ,[ScoreUser20]
                                              ,[ScoreUser21]
                                              ,[ScoreUser22]
                                              ,[ScoreUser23]
                                              ,[ScoreUser24]
                                              ,[ScoreUser25]
                                              ,[ScoreUser26]
                                              ,[ScoreUser27]
                                              ,[ScoreUser28]
                                              ,[ScoreUser29]
                                              ,[ScoreUser30]
                                              ,[ScoreUser31]
                                              ,[ScoreUser32]
                                              ,[ScoreUser33]
                                              ,[ScoreUser34]
                                              ,[ScoreUser35]
                                              ,[ScoreUser36]
                                              ,[ScoreUser37]
                                              ,[ScoreUser38]
                                              ,[ScoreUser39]
                                              ,[ScoreUser40]
                                              ,[ScoreUser41]
                                              ,[ScoreUser42]
                                              ,[ScoreUser43]
                                              ,[ScoreUser44]
                                              ,[ScoreUser45]
                                              ,[ScoreUser46]
                                              ,[ScoreUser47]
                                              ,[ScoreUser48]
                                              ,[ScoreUser49]
                                              ,[ScoreUser50]
                                              ,[ScoreUser51]
                                              ,[ScoreUser52]
                                              ,[ScoreUser53]
                                              ,[ScoreUser54]
                                              ,[ScoreUser55]
                                              ,[ScoreUser56]
                                              ,[ScoreUser57]
                                              ,[ScoreUser58]
                                              ,[ScoreUser59]
                                              ,[ScoreUser60]
                                              ,[ScoreUser61]
                                              ,[ScoreUser62]
                                              ,[ScoreUser63]
                                              ,[ScoreUser64]
                                              ,[ScoreUser65]
                                              ,[ScoreUser66]
                                              ,[ScoreUser67]
                                              ,[StatusUser1]
                                              ,[StatusUser2]
                                              ,[StatusUser3]
                                              ,[StatusUser4]
                                              ,[StatusUser5]
                                              ,[StatusUser6]
                                              ,[StatusUser7]
                                              ,[StatusUser8]
                                              ,[StatusUser9]
                                              ,[StatusUser10]
                                              ,[StatusUser11]
                                              ,[StatusUser12]
                                              ,[StatusUser13]
                                              ,[StatusUser14]
                                              ,[StatusUser15]
                                              ,[StatusUser16]
                                              ,[StatusUser17]
                                              ,[StatusUser18]
                                              ,[StatusUser19]
                                              ,[StatusUser20]
                                              ,[StatusUser21]
                                              ,[StatusUser22]
                                              ,[StatusUser23]
                                              ,[StatusUser24]
                                              ,[StatusUser25]
                                              ,[StatusUser26]
                                              ,[StatusUser27]
                                              ,[StatusUser28]
                                              ,[StatusUser29]
                                              ,[StatusUser30]
                                              ,[StatusUser31]
                                              ,[StatusUser32]
                                              ,[StatusUser33]
                                              ,[StatusUser34]
                                              ,[StatusUser35]
                                              ,[StatusUser36]
                                              ,[StatusUser37]
                                              ,[StatusUser38]
                                              ,[StatusUser39]
                                              ,[StatusUser40]
                                              ,[StatusUser41]
                                              ,[StatusUser42]
                                              ,[StatusUser43]
                                              ,[StatusUser44]
                                              ,[StatusUser45]
                                              ,[StatusUser46]
                                              ,[StatusUser47]
                                              ,[StatusUser48]
                                              ,[StatusUser49]
                                              ,[StatusUser50]
                                              ,[StatusUser51]
                                              ,[StatusUser52]
                                              ,[StatusUser53]
                                              ,[StatusUser54]
                                              ,[StatusUser55]
                                              ,[StatusUser56]
                                              ,[StatusUser57]
                                              ,[StatusUser58]
                                              ,[StatusUser59]
                                              ,[StatusUser60]
                                              ,[StatusUser61]
                                              ,[StatusUser62]
                                              ,[StatusUser63]
                                              ,[StatusUser64]
                                              ,[StatusUser65]
                                              ,[StatusUser66]
                                              ,[StatusUser67]
                                              ,[SuccessfulAuctionCountUser1]
                                              ,[SuccessfulAuctionCountUser2]
                                              ,[SuccessfulAuctionCountUser3]
                                              ,[SuccessfulAuctionCountUser4]
                                              ,[SuccessfulAuctionCountUser5]
                                              ,[SuccessfulAuctionCountUser6]
                                              ,[SuccessfulAuctionCountUser7]
                                              ,[SuccessfulAuctionCountUser8]
                                              ,[SuccessfulAuctionCountUser9]
                                              ,[SuccessfulAuctionCountUser10]
                                              ,[SuccessfulAuctionCountUser11]
                                              ,[SuccessfulAuctionCountUser12]
                                              ,[SuccessfulAuctionCountUser13]
                                              ,[SuccessfulAuctionCountUser14]
                                              ,[SuccessfulAuctionCountUser15]
                                              ,[SuccessfulAuctionCountUser16]
                                              ,[SuccessfulAuctionCountUser17]
                                              ,[SuccessfulAuctionCountUser18]
                                              ,[SuccessfulAuctionCountUser19]
                                              ,[SuccessfulAuctionCountUser20]
                                              ,[SuccessfulAuctionCountUser21]
                                              ,[SuccessfulAuctionCountUser22]
                                              ,[SuccessfulAuctionCountUser23]
                                              ,[SuccessfulAuctionCountUser24]
                                              ,[SuccessfulAuctionCountUser25]
                                              ,[SuccessfulAuctionCountUser26]
                                              ,[SuccessfulAuctionCountUser27]
                                              ,[SuccessfulAuctionCountUser28]
                                              ,[SuccessfulAuctionCountUser29]
                                              ,[SuccessfulAuctionCountUser30]
                                              ,[SuccessfulAuctionCountUser31]
                                              ,[SuccessfulAuctionCountUser32]
                                              ,[SuccessfulAuctionCountUser33]
                                              ,[SuccessfulAuctionCountUser34]
                                              ,[SuccessfulAuctionCountUser35]
                                              ,[SuccessfulAuctionCountUser36]
                                              ,[SuccessfulAuctionCountUser37]
                                              ,[SuccessfulAuctionCountUser38]
                                              ,[SuccessfulAuctionCountUser39]
                                              ,[SuccessfulAuctionCountUser40]
                                              ,[SuccessfulAuctionCountUser41]
                                              ,[SuccessfulAuctionCountUser42]
                                              ,[SuccessfulAuctionCountUser43]
                                              ,[SuccessfulAuctionCountUser44]
                                              ,[SuccessfulAuctionCountUser45]
                                              ,[SuccessfulAuctionCountUser46]
                                              ,[SuccessfulAuctionCountUser47]
                                              ,[SuccessfulAuctionCountUser48]
                                              ,[SuccessfulAuctionCountUser49]
                                              ,[SuccessfulAuctionCountUser50]
                                              ,[SuccessfulAuctionCountUser51]
                                              ,[SuccessfulAuctionCountUser52]
                                              ,[SuccessfulAuctionCountUser53]
                                              ,[SuccessfulAuctionCountUser54]
                                              ,[SuccessfulAuctionCountUser55]
                                              ,[SuccessfulAuctionCountUser56]
                                              ,[SuccessfulAuctionCountUser57]
                                              ,[SuccessfulAuctionCountUser58]
                                              ,[SuccessfulAuctionCountUser59]
                                              ,[SuccessfulAuctionCountUser60]
                                              ,[SuccessfulAuctionCountUser61]
                                              ,[SuccessfulAuctionCountUser62]
                                              ,[SuccessfulAuctionCountUser63]
                                              ,[SuccessfulAuctionCountUser64]
                                              ,[SuccessfulAuctionCountUser65]
                                              ,[SuccessfulAuctionCountUser66]
                                              ,[SuccessfulAuctionCountUser67]
                                              ,[WalletUser1]
                                              ,[WalletUser2]
                                              ,[WalletUser3]
                                              ,[WalletUser4]
                                              ,[WalletUser5]
                                              ,[WalletUser6]
                                              ,[WalletUser7]
                                              ,[WalletUser8]
                                              ,[WalletUser9]
                                              ,[WalletUser10]
                                              ,[WalletUser11]
                                              ,[WalletUser12]
                                              ,[WalletUser13]
                                              ,[WalletUser14]
                                              ,[WalletUser15]
                                              ,[WalletUser16]
                                              ,[WalletUser17]
                                              ,[WalletUser18]
                                              ,[WalletUser19]
                                              ,[WalletUser20]
                                              ,[WalletUser21]
                                              ,[WalletUser22]
                                              ,[WalletUser23]
                                              ,[WalletUser24]
                                              ,[WalletUser25]
                                              ,[WalletUser26]
                                              ,[WalletUser27]
                                              ,[WalletUser28]
                                              ,[WalletUser29]
                                              ,[WalletUser30]
                                              ,[WalletUser31]
                                              ,[WalletUser32]
                                              ,[WalletUser33]
                                              ,[WalletUser34]
                                              ,[WalletUser35]
                                              ,[WalletUser36]
                                              ,[WalletUser37]
                                              ,[WalletUser38]
                                              ,[WalletUser39]
                                              ,[WalletUser40]
                                              ,[WalletUser41]
                                              ,[WalletUser42]
                                              ,[WalletUser43]
                                              ,[WalletUser44]
                                              ,[WalletUser45]
                                              ,[WalletUser46]
                                              ,[WalletUser47]
                                              ,[WalletUser48]
                                              ,[WalletUser49]
                                              ,[WalletUser50]
                                              ,[WalletUser51]
                                              ,[WalletUser52]
                                              ,[WalletUser53]
                                              ,[WalletUser54]
                                              ,[WalletUser55]
                                              ,[WalletUser56]
                                              ,[WalletUser57]
                                              ,[WalletUser58]
                                              ,[WalletUser59]
                                              ,[WalletUser60]
                                              ,[WalletUser61]
                                              ,[WalletUser62]
                                              ,[WalletUser63]
                                              ,[WalletUser64]
                                              ,[WalletUser65]
                                              ,[WalletUser66]
                                              ,[WalletUser67]
                                              ,[AuctionPrice])
                                        VALUES
                                              (<TimeStamp>
                                              ,<LogType>
                                              ,<TransactionID>
                                              ,<AllocatedChannel>
                                              ,<WinnerSecondaryUserID>
                                              ,<WinnerSecondaryUserWallet>
                                              ,<WinnerSecondaryUserReputationScore>
                                              ,<PrimaryUserID>
                                              ,<PrimaryUserWallet>
                                              ,<PrimaryUserReputationScore>
                                              ,<PrimaryUserStatus>
                                              ,<AuctionNo>
                                              ,<AuctionChannel>
                                              ,<AuctionChannelBandwidth>
                                              ,<PrimaryUserAuctionCount>
                                              ,<PrimaryUserSuccessfulAuctionCount>
                                              ,<ResponseIsAppropriate>
                                              ,<AppropriateResponseCount>
                                              ,<TotalRequestCount>
                                              ,<AvailableSpectrumKHz>
                                              ,<TotalSpectrumKHz>
                                              ,<Channel1>
                                              ,<Channel2>
                                              ,<Channel3>
                                              ,<Channel4>
                                              ,<Channel5>
                                              ,<Channel6>
                                              ,<Channel7>
                                              ,<Channel8>
                                              ,<Channel9>
                                              ,<Channel10>
                                              ,<Channel11>
                                              ,<Channel12>
                                              ,<Channel13>
                                              ,<Channel14>
                                              ,<Channel15>
                                              ,<Channel16>
                                              ,<Channel17>
                                              ,<Channel18>
                                              ,<Channel19>
                                              ,<Channel20>
                                              ,<Channel21>
                                              ,<Channel22>
                                              ,<Channel23>
                                              ,<Channel24>
                                              ,<Channel25>
                                              ,<Channel26>
                                              ,<Channel27>
                                              ,<Channel28>
                                              ,<Channel29>
                                              ,<Channel30>
                                              ,<Channel31>
                                              ,<Channel32>
                                              ,<Channel33>
                                              ,<Channel34>
                                              ,<Channel35>
                                              ,<Channel36>
                                              ,<Channel37>
                                              ,<Channel38>
                                              ,<Channel39>
                                              ,<Channel40>
                                              ,<Channel41>
                                              ,<Channel42>
                                              ,<Channel43>
                                              ,<Channel44>
                                              ,<Channel45>
                                              ,<Channel46>
                                              ,<Channel47>
                                              ,<Channel48>
                                              ,<Channel49>
                                              ,<Channel50>
                                              ,<Channel51>
                                              ,<Channel52>
                                              ,<Channel53>
                                              ,<Channel54>
                                              ,<Channel55>
                                              ,<Channel56>
                                              ,<Channel57>
                                              ,<AuctionCountUser1>
                                              ,<AuctionCountUser2>
                                              ,<AuctionCountUser3>
                                              ,<AuctionCountUser4>
                                              ,<AuctionCountUser5>
                                              ,<AuctionCountUser6>
                                              ,<AuctionCountUser7>
                                              ,<AuctionCountUser8>
                                              ,<AuctionCountUser9>
                                              ,<AuctionCountUser10>
                                              ,<AuctionCountUser11>
                                              ,<AuctionCountUser12>
                                              ,<AuctionCountUser13>
                                              ,<AuctionCountUser14>
                                              ,<AuctionCountUser15>
                                              ,<AuctionCountUser16>
                                              ,<AuctionCountUser17>
                                              ,<AuctionCountUser18>
                                              ,<AuctionCountUser19>
                                              ,<AuctionCountUser20>
                                              ,<AuctionCountUser21>
                                              ,<AuctionCountUser22>
                                              ,<AuctionCountUser23>
                                              ,<AuctionCountUser24>
                                              ,<AuctionCountUser25>
                                              ,<AuctionCountUser26>
                                              ,<AuctionCountUser27>
                                              ,<AuctionCountUser28>
                                              ,<AuctionCountUser29>
                                              ,<AuctionCountUser30>
                                              ,<AuctionCountUser31>
                                              ,<AuctionCountUser32>
                                              ,<AuctionCountUser33>
                                              ,<AuctionCountUser34>
                                              ,<AuctionCountUser35>
                                              ,<AuctionCountUser36>
                                              ,<AuctionCountUser37>
                                              ,<AuctionCountUser38>
                                              ,<AuctionCountUser39>
                                              ,<AuctionCountUser40>
                                              ,<AuctionCountUser41>
                                              ,<AuctionCountUser42>
                                              ,<AuctionCountUser43>
                                              ,<AuctionCountUser44>
                                              ,<AuctionCountUser45>
                                              ,<AuctionCountUser46>
                                              ,<AuctionCountUser47>
                                              ,<AuctionCountUser48>
                                              ,<AuctionCountUser49>
                                              ,<AuctionCountUser50>
                                              ,<AuctionCountUser51>
                                              ,<AuctionCountUser52>
                                              ,<AuctionCountUser53>
                                              ,<AuctionCountUser54>
                                              ,<AuctionCountUser55>
                                              ,<AuctionCountUser56>
                                              ,<AuctionCountUser57>
                                              ,<AuctionCountUser58>
                                              ,<AuctionCountUser59>
                                              ,<AuctionCountUser60>
                                              ,<AuctionCountUser61>
                                              ,<AuctionCountUser62>
                                              ,<AuctionCountUser63>
                                              ,<AuctionCountUser64>
                                              ,<AuctionCountUser65>
                                              ,<AuctionCountUser66>
                                              ,<AuctionCountUser67>
                                              ,<IsBiddingUser1>
                                              ,<IsBiddingUser2>
                                              ,<IsBiddingUser3>
                                              ,<IsBiddingUser4>
                                              ,<IsBiddingUser5>
                                              ,<IsBiddingUser6>
                                              ,<IsBiddingUser7>
                                              ,<IsBiddingUser8>
                                              ,<IsBiddingUser9>
                                              ,<IsBiddingUser10>
                                              ,<IsBiddingUser11>
                                              ,<IsBiddingUser12>
                                              ,<IsBiddingUser13>
                                              ,<IsBiddingUser14>
                                              ,<IsBiddingUser15>
                                              ,<IsBiddingUser16>
                                              ,<IsBiddingUser17>
                                              ,<IsBiddingUser18>
                                              ,<IsBiddingUser19>
                                              ,<IsBiddingUser20>
                                              ,<IsBiddingUser21>
                                              ,<IsBiddingUser22>
                                              ,<IsBiddingUser23>
                                              ,<IsBiddingUser24>
                                              ,<IsBiddingUser25>
                                              ,<IsBiddingUser26>
                                              ,<IsBiddingUser27>
                                              ,<IsBiddingUser28>
                                              ,<IsBiddingUser29>
                                              ,<IsBiddingUser30>
                                              ,<IsBiddingUser31>
                                              ,<IsBiddingUser32>
                                              ,<IsBiddingUser33>
                                              ,<IsBiddingUser34>
                                              ,<IsBiddingUser35>
                                              ,<IsBiddingUser36>
                                              ,<IsBiddingUser37>
                                              ,<IsBiddingUser38>
                                              ,<IsBiddingUser39>
                                              ,<IsBiddingUser40>
                                              ,<IsBiddingUser41>
                                              ,<IsBiddingUser42>
                                              ,<IsBiddingUser43>
                                              ,<IsBiddingUser44>
                                              ,<IsBiddingUser45>
                                              ,<IsBiddingUser46>
                                              ,<IsBiddingUser47>
                                              ,<IsBiddingUser48>
                                              ,<IsBiddingUser49>
                                              ,<IsBiddingUser50>
                                              ,<IsBiddingUser51>
                                              ,<IsBiddingUser52>
                                              ,<IsBiddingUser53>
                                              ,<IsBiddingUser54>
                                              ,<IsBiddingUser55>
                                              ,<IsBiddingUser56>
                                              ,<IsBiddingUser57>
                                              ,<IsBiddingUser58>
                                              ,<IsBiddingUser59>
                                              ,<IsBiddingUser60>
                                              ,<IsBiddingUser61>
                                              ,<IsBiddingUser62>
                                              ,<IsBiddingUser63>
                                              ,<IsBiddingUser64>
                                              ,<IsBiddingUser65>
                                              ,<IsBiddingUser66>
                                              ,<IsBiddingUser67>
                                              ,<IsInPoolUser1>
                                              ,<IsInPoolUser2>
                                              ,<IsInPoolUser3>
                                              ,<IsInPoolUser4>
                                              ,<IsInPoolUser5>
                                              ,<IsInPoolUser6>
                                              ,<IsInPoolUser7>
                                              ,<IsInPoolUser8>
                                              ,<IsInPoolUser9>
                                              ,<IsInPoolUser10>
                                              ,<IsInPoolUser11>
                                              ,<IsInPoolUser12>
                                              ,<IsInPoolUser13>
                                              ,<IsInPoolUser14>
                                              ,<IsInPoolUser15>
                                              ,<IsInPoolUser16>
                                              ,<IsInPoolUser17>
                                              ,<IsInPoolUser18>
                                              ,<IsInPoolUser19>
                                              ,<IsInPoolUser20>
                                              ,<IsInPoolUser21>
                                              ,<IsInPoolUser22>
                                              ,<IsInPoolUser23>
                                              ,<IsInPoolUser24>
                                              ,<IsInPoolUser25>
                                              ,<IsInPoolUser26>
                                              ,<IsInPoolUser27>
                                              ,<IsInPoolUser28>
                                              ,<IsInPoolUser29>
                                              ,<IsInPoolUser30>
                                              ,<IsInPoolUser31>
                                              ,<IsInPoolUser32>
                                              ,<IsInPoolUser33>
                                              ,<IsInPoolUser34>
                                              ,<IsInPoolUser35>
                                              ,<IsInPoolUser36>
                                              ,<IsInPoolUser37>
                                              ,<IsInPoolUser38>
                                              ,<IsInPoolUser39>
                                              ,<IsInPoolUser40>
                                              ,<IsInPoolUser41>
                                              ,<IsInPoolUser42>
                                              ,<IsInPoolUser43>
                                              ,<IsInPoolUser44>
                                              ,<IsInPoolUser45>
                                              ,<IsInPoolUser46>
                                              ,<IsInPoolUser47>
                                              ,<IsInPoolUser48>
                                              ,<IsInPoolUser49>
                                              ,<IsInPoolUser50>
                                              ,<IsInPoolUser51>
                                              ,<IsInPoolUser52>
                                              ,<IsInPoolUser53>
                                              ,<IsInPoolUser54>
                                              ,<IsInPoolUser55>
                                              ,<IsInPoolUser56>
                                              ,<IsInPoolUser57>
                                              ,<IsInPoolUser58>
                                              ,<IsInPoolUser59>
                                              ,<IsInPoolUser60>
                                              ,<IsInPoolUser61>
                                              ,<IsInPoolUser62>
                                              ,<IsInPoolUser63>
                                              ,<IsInPoolUser64>
                                              ,<IsInPoolUser65>
                                              ,<IsInPoolUser66>
                                              ,<IsInPoolUser67>
                                              ,<ScoreUser1>
                                              ,<ScoreUser2>
                                              ,<ScoreUser3>
                                              ,<ScoreUser4>
                                              ,<ScoreUser5>
                                              ,<ScoreUser6>
                                              ,<ScoreUser7>
                                              ,<ScoreUser8>
                                              ,<ScoreUser9>
                                              ,<ScoreUser10>
                                              ,<ScoreUser11>
                                              ,<ScoreUser12>
                                              ,<ScoreUser13>
                                              ,<ScoreUser14>
                                              ,<ScoreUser15>
                                              ,<ScoreUser16>
                                              ,<ScoreUser17>
                                              ,<ScoreUser18>
                                              ,<ScoreUser19>
                                              ,<ScoreUser20>
                                              ,<ScoreUser21>
                                              ,<ScoreUser22>
                                              ,<ScoreUser23>
                                              ,<ScoreUser24>
                                              ,<ScoreUser25>
                                              ,<ScoreUser26>
                                              ,<ScoreUser27>
                                              ,<ScoreUser28>
                                              ,<ScoreUser29>
                                              ,<ScoreUser30>
                                              ,<ScoreUser31>
                                              ,<ScoreUser32>
                                              ,<ScoreUser33>
                                              ,<ScoreUser34>
                                              ,<ScoreUser35>
                                              ,<ScoreUser36>
                                              ,<ScoreUser37>
                                              ,<ScoreUser38>
                                              ,<ScoreUser39>
                                              ,<ScoreUser40>
                                              ,<ScoreUser41>
                                              ,<ScoreUser42>
                                              ,<ScoreUser43>
                                              ,<ScoreUser44>
                                              ,<ScoreUser45>
                                              ,<ScoreUser46>
                                              ,<ScoreUser47>
                                              ,<ScoreUser48>
                                              ,<ScoreUser49>
                                              ,<ScoreUser50>
                                              ,<ScoreUser51>
                                              ,<ScoreUser52>
                                              ,<ScoreUser53>
                                              ,<ScoreUser54>
                                              ,<ScoreUser55>
                                              ,<ScoreUser56>
                                              ,<ScoreUser57>
                                              ,<ScoreUser58>
                                              ,<ScoreUser59>
                                              ,<ScoreUser60>
                                              ,<ScoreUser61>
                                              ,<ScoreUser62>
                                              ,<ScoreUser63>
                                              ,<ScoreUser64>
                                              ,<ScoreUser65>
                                              ,<ScoreUser66>
                                              ,<ScoreUser67>
                                              ,<StatusUser1>
                                              ,<StatusUser2>
                                              ,<StatusUser3>
                                              ,<StatusUser4>
                                              ,<StatusUser5>
                                              ,<StatusUser6>
                                              ,<StatusUser7>
                                              ,<StatusUser8>
                                              ,<StatusUser9>
                                              ,<StatusUser10>
                                              ,<StatusUser11>
                                              ,<StatusUser12>
                                              ,<StatusUser13>
                                              ,<StatusUser14>
                                              ,<StatusUser15>
                                              ,<StatusUser16>
                                              ,<StatusUser17>
                                              ,<StatusUser18>
                                              ,<StatusUser19>
                                              ,<StatusUser20>
                                              ,<StatusUser21>
                                              ,<StatusUser22>
                                              ,<StatusUser23>
                                              ,<StatusUser24>
                                              ,<StatusUser25>
                                              ,<StatusUser26>
                                              ,<StatusUser27>
                                              ,<StatusUser28>
                                              ,<StatusUser29>
                                              ,<StatusUser30>
                                              ,<StatusUser31>
                                              ,<StatusUser32>
                                              ,<StatusUser33>
                                              ,<StatusUser34>
                                              ,<StatusUser35>
                                              ,<StatusUser36>
                                              ,<StatusUser37>
                                              ,<StatusUser38>
                                              ,<StatusUser39>
                                              ,<StatusUser40>
                                              ,<StatusUser41>
                                              ,<StatusUser42>
                                              ,<StatusUser43>
                                              ,<StatusUser44>
                                              ,<StatusUser45>
                                              ,<StatusUser46>
                                              ,<StatusUser47>
                                              ,<StatusUser48>
                                              ,<StatusUser49>
                                              ,<StatusUser50>
                                              ,<StatusUser51>
                                              ,<StatusUser52>
                                              ,<StatusUser53>
                                              ,<StatusUser54>
                                              ,<StatusUser55>
                                              ,<StatusUser56>
                                              ,<StatusUser57>
                                              ,<StatusUser58>
                                              ,<StatusUser59>
                                              ,<StatusUser60>
                                              ,<StatusUser61>
                                              ,<StatusUser62>
                                              ,<StatusUser63>
                                              ,<StatusUser64>
                                              ,<StatusUser65>
                                              ,<StatusUser66>
                                              ,<StatusUser67>
                                              ,<SuccessfulAuctionCountUser1>
                                              ,<SuccessfulAuctionCountUser2>
                                              ,<SuccessfulAuctionCountUser3>
                                              ,<SuccessfulAuctionCountUser4>
                                              ,<SuccessfulAuctionCountUser5>
                                              ,<SuccessfulAuctionCountUser6>
                                              ,<SuccessfulAuctionCountUser7>
                                              ,<SuccessfulAuctionCountUser8>
                                              ,<SuccessfulAuctionCountUser9>
                                              ,<SuccessfulAuctionCountUser10>
                                              ,<SuccessfulAuctionCountUser11>
                                              ,<SuccessfulAuctionCountUser12>
                                              ,<SuccessfulAuctionCountUser13>
                                              ,<SuccessfulAuctionCountUser14>
                                              ,<SuccessfulAuctionCountUser15>
                                              ,<SuccessfulAuctionCountUser16>
                                              ,<SuccessfulAuctionCountUser17>
                                              ,<SuccessfulAuctionCountUser18>
                                              ,<SuccessfulAuctionCountUser19>
                                              ,<SuccessfulAuctionCountUser20>
                                              ,<SuccessfulAuctionCountUser21>
                                              ,<SuccessfulAuctionCountUser22>
                                              ,<SuccessfulAuctionCountUser23>
                                              ,<SuccessfulAuctionCountUser24>
                                              ,<SuccessfulAuctionCountUser25>
                                              ,<SuccessfulAuctionCountUser26>
                                              ,<SuccessfulAuctionCountUser27>
                                              ,<SuccessfulAuctionCountUser28>
                                              ,<SuccessfulAuctionCountUser29>
                                              ,<SuccessfulAuctionCountUser30>
                                              ,<SuccessfulAuctionCountUser31>
                                              ,<SuccessfulAuctionCountUser32>
                                              ,<SuccessfulAuctionCountUser33>
                                              ,<SuccessfulAuctionCountUser34>
                                              ,<SuccessfulAuctionCountUser35>
                                              ,<SuccessfulAuctionCountUser36>
                                              ,<SuccessfulAuctionCountUser37>
                                              ,<SuccessfulAuctionCountUser38>
                                              ,<SuccessfulAuctionCountUser39>
                                              ,<SuccessfulAuctionCountUser40>
                                              ,<SuccessfulAuctionCountUser41>
                                              ,<SuccessfulAuctionCountUser42>
                                              ,<SuccessfulAuctionCountUser43>
                                              ,<SuccessfulAuctionCountUser44>
                                              ,<SuccessfulAuctionCountUser45>
                                              ,<SuccessfulAuctionCountUser46>
                                              ,<SuccessfulAuctionCountUser47>
                                              ,<SuccessfulAuctionCountUser48>
                                              ,<SuccessfulAuctionCountUser49>
                                              ,<SuccessfulAuctionCountUser50>
                                              ,<SuccessfulAuctionCountUser51>
                                              ,<SuccessfulAuctionCountUser52>
                                              ,<SuccessfulAuctionCountUser53>
                                              ,<SuccessfulAuctionCountUser54>
                                              ,<SuccessfulAuctionCountUser55>
                                              ,<SuccessfulAuctionCountUser56>
                                              ,<SuccessfulAuctionCountUser57>
                                              ,<SuccessfulAuctionCountUser58>
                                              ,<SuccessfulAuctionCountUser59>
                                              ,<SuccessfulAuctionCountUser60>
                                              ,<SuccessfulAuctionCountUser61>
                                              ,<SuccessfulAuctionCountUser62>
                                              ,<SuccessfulAuctionCountUser63>
                                              ,<SuccessfulAuctionCountUser64>
                                              ,<SuccessfulAuctionCountUser65>
                                              ,<SuccessfulAuctionCountUser66>
                                              ,<SuccessfulAuctionCountUser67>
                                              ,<WalletUser1>
                                              ,<WalletUser2>
                                              ,<WalletUser3>
                                              ,<WalletUser4>
                                              ,<WalletUser5>
                                              ,<WalletUser6>
                                              ,<WalletUser7>
                                              ,<WalletUser8>
                                              ,<WalletUser9>
                                              ,<WalletUser10>
                                              ,<WalletUser11>
                                              ,<WalletUser12>
                                              ,<WalletUser13>
                                              ,<WalletUser14>
                                              ,<WalletUser15>
                                              ,<WalletUser16>
                                              ,<WalletUser17>
                                              ,<WalletUser18>
                                              ,<WalletUser19>
                                              ,<WalletUser20>
                                              ,<WalletUser21>
                                              ,<WalletUser22>
                                              ,<WalletUser23>
                                              ,<WalletUser24>
                                              ,<WalletUser25>
                                              ,<WalletUser26>
                                              ,<WalletUser27>
                                              ,<WalletUser28>
                                              ,<WalletUser29>
                                              ,<WalletUser30>
                                              ,<WalletUser31>
                                              ,<WalletUser32>
                                              ,<WalletUser33>
                                              ,<WalletUser34>
                                              ,<WalletUser35>
                                              ,<WalletUser36>
                                              ,<WalletUser37>
                                              ,<WalletUser38>
                                              ,<WalletUser39>
                                              ,<WalletUser40>
                                              ,<WalletUser41>
                                              ,<WalletUser42>
                                              ,<WalletUser43>
                                              ,<WalletUser44>
                                              ,<WalletUser45>
                                              ,<WalletUser46>
                                              ,<WalletUser47>
                                              ,<WalletUser48>
                                              ,<WalletUser49>
                                              ,<WalletUser50>
                                              ,<WalletUser51>
                                              ,<WalletUser52>
                                              ,<WalletUser53>
                                              ,<WalletUser54>
                                              ,<WalletUser55>
                                              ,<WalletUser56>
                                              ,<WalletUser57>
                                              ,<WalletUser58>
                                              ,<WalletUser59>
                                              ,<WalletUser60>
                                              ,<WalletUser61>
                                              ,<WalletUser62>
                                              ,<WalletUser63>
                                              ,<WalletUser64>
                                              ,<WalletUser65>
                                              ,<WalletUser66>
                                              ,<WalletUser67>
                                              ,<AuctionPrice>)";

        public static string selectLatestRow = @"  SELECT TOP(1) *
                                            FROM [SpectrumSharingDB].[dbo].[TransactionLog] WITH (SNAPSHOT)
                                            ORDER BY TimeStamp desc";
        public static int InsertEvent(string [,] parametersAndValues)
        {
            string insertQueryCopy=insertQuery;

                for (int i = 0; i < 548; i++)
                    insertQueryCopy = insertQueryCopy.Replace("<" + parametersAndValues[i,0] +">", parametersAndValues[i,1]);
            
            int affectedRowCount = 0;
            using (SqlConnection conn = new(connectDB))
            {
                conn.Open();

                using SqlCommand cmd = new(insertQueryCopy, conn);
                affectedRowCount = cmd.ExecuteNonQuery();
            }
            return affectedRowCount;
        }

        public static DataTable SelectLatestRow()
        {
            string selectCommand = selectLatestRow;
            SqlConnection connection = new SqlConnection(connectDB);
            connection.Open();
            DataTable result = new DataTable();
            SqlDataAdapter adapter = new SqlDataAdapter(selectCommand, connection);
            adapter.Fill(result);
            connection.Close();
            return result;
        }
    }
}
